version: '3.9'
services:
  distribution: 
    build:  ./distribution/
    expose:
    - 5001
    ports:
    - "5001:5001"
  focus_factor: 
    build:  ./focus_factor/
    expose:
    - 5002
    ports:
    - "5002:5002"